#ifndef _VERSION_H_
#define _VERSION_H_
#pragma once

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VERSION_MAJOR				1
#define VERSION_MINOR				11
#define VERSION_REVISION			0
#define VERSION_BUILD				0

#if VERSION_BUILD == 0
#define PLUGIN_VERSION_STR			STRINGIZE(VERSION_MAJOR)		\
									"." STRINGIZE(VERSION_MINOR)	\
									"." STRINGIZE(VERSION_REVISION)
#else
#define PLUGIN_VERSION_STR			STRINGIZE(VERSION_MAJOR)		\
									"." STRINGIZE(VERSION_MINOR)	\
									"." STRINGIZE(VERSION_REVISION)	\
									" rev " STRINGIZE(VERSION_BUILD)
#endif

#define VER_COMPANY_NAME_STR		"Adam Biser"
#define VER_FILE_DESCRIPTION_STR	"A plugin to allow games developed using AppGameKit Tier 1 to use the Steamworks API."
#define VER_FILE_VERSION			VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_BUILD
#define VER_FILE_VERSION_STR		STRINGIZE(VERSION_MAJOR)		\
									"." STRINGIZE(VERSION_MINOR)	\
									"." STRINGIZE(VERSION_REVISION)	\
									"." STRINGIZE(VERSION_BUILD)

#define VER_PRODUCTNAME_STR			"SteamPlugin.dll"
#define VER_PRODUCT_VERSION			VER_FILE_VERSION
#define VER_PRODUCT_VERSION_STR		VER_FILE_VERSION_STR
#define VER_ORIGINAL_FILENAME_STR	"SteamPlugin.dll"
#define VER_INTERNAL_NAME_STR		VER_ORIGINAL_FILENAME_STR
#define VER_COPYRIGHT_STR			"Copyright (C) 2023"

#endif
